version: '3'
services:
  sync:
    image: waisbrot/wait
    depends_on:
      - auth
      - swagger-validator
      - postgres
      - rabbitmq
    environment:
      TARGETS: "auth:9497 swagger-validator:8080 postgres:5432 rabbitmq:5672"
      TIMEOUT: "${INTEGRATION_TEST_TIMEOUT}"
  auth:
    image: wazopbx/wazo-auth-tests
    ports:
      - "9497"
    environment:
      XIVO_UUID: "ad094f0b-8597-4129-a9c9-134993543120"
    volumes:
      - "../../..:/usr/src/wazo-auth"
      - "./etc/wazo-auth/config.yml:/etc/wazo-auth/config.yml"
      # - "${LOCAL_GIT_REPOS}/xivo-lib-python/xivo:/usr/local/lib/python2.7/site-packages/xivo"
      # - "${LOCAL_GIT_REPOS}/xivo-bus/xivo_bus:/usr/local/lib/python2.7/site-packages/xivo_bus"
    command: "wazo-auth"
  swagger-validator:
    image: swaggerapi/swagger-validator
    ports:
      - "8080"
  postgres:
    image: wazopbx/wazo-auth-db
    expose:
      - "5432"
  rabbitmq:
    image: rabbitmq
    ports:
      - "5672"
